export const TEXTS = {
  tr: {
    header: 'CINEMAMOOD',
    subHeader: 'Sadece en iyiler, sadece senin için.',
    btnMain: 'Rastgele Film Bul 🎲',
    btnMood: 'Moduna Göre Seç 🎭',
    genreTitle: 'NASIL HİSSEDİYORSUN?',
    favHeader: '❤️ FAVORİLERİM',
    watchlistHeader: '📋 İZLEME LİSTEM',
    manageList: 'DÜZENLE ✏️',
    manageTitle: 'LİSTEYİ DÜZENLE',
    emptyList: 'Listen bomboş! Biraz film ekle.',
    loading: 'Veritabanı taranıyor...',
    watchLabel: 'TR\'DE BURADA:',
    noPlatform: 'Dijitalde Yok',
    trailer: '▶ FRAGMANI İZLE',
    cast: 'OYUNCULAR',
    crew: 'FİLM EKİBİ',
    btnAgain: '🎲 BAŞKA ÖNER',
    btnBack: 'Ana Sayfaya Dön',
    connErr: 'Bağlantı Hatası',
    noInfo: 'Bilgi Yok'
  },
  en: {
    header: 'CINEMAMOOD',
    subHeader: 'Only the best, tailored for you.',
    btnMain: 'Find Random Movie 🎲',
    btnMood: 'Choose by Mood 🎭',
    genreTitle: 'HOW DO YOU FEEL?',
    favHeader: '❤️ MY FAVORITES',
    watchlistHeader: '📋 WATCHLIST',
    manageList: 'EDIT ✏️',
    manageTitle: 'MANAGE LIST',
    emptyList: 'Your list is empty! Add some movies.',
    loading: 'Scanning database...',
    watchLabel: 'WATCH IN US:',
    noPlatform: 'Not on Digital',
    trailer: '▶ WATCH TRAILER',
    cast: 'CAST',
    crew: 'CREW',
    btnAgain: '🎲 SUGGEST ANOTHER',
    btnBack: 'Back to Home',
    connErr: 'Connection Error',
    noInfo: 'No Info'
  }
};